### ISSUE TITLE
I'm filing a DMCA takedown. Don't steal my work.

### ISSUE THREAD

**Issue by lol-jude** [GlixzzyBlooketHacks/Glixzzy.github.io.#1]
Hack approved

**Comment by lol-jude** [comment]
I know this is stolen because you took my READ.md and changed the name

**Comment by GlixzzyBlooketHacks** [comment]
> I know this is stolen because you took my READ.md and changed the name

I just looked up blooket hacks yesterday and got the hacks yea i copied the read.md but im still making changes and my friends finding more hacks so chill dawg im not stealing your work i like the work your doing

**Comment by GlixzzyBlooketHacks** [comment]
> Hack approved
