### ISSUE TITLE
@glixxzzy

### ISSUE THREAD

**Issue by VillainsRule4000** [GlixzzyBlooketHacks/Glixzzy.github.io.#14]
I love how @glixxzzy (formerly @lol-jude) is now impersonating Glixzzy, when he complained at you for doing so...

**Comment by hecker1834** [comment]
BRUHHHHHHHHHHHHHh

**Comment by RattyBoi** [comment]
That is just sad. He also blocked me so I can't star his repository and I also can't file any new issues or complaints.

**Comment by VillainsRule4000** [comment]
@RattyBoi Yeah, IKR!

**Comment by hecker1834** [comment]
ok?

**Comment by hecker1834** [comment]
did you guys hear the news

**Comment by VillainsRule4000** [comment]
@hecker1834 There's a lot of news, what is it?

**Comment by hecker1834** [comment]
the 19 children killed in texas

**Comment by RattyBoi** [comment]
> the 19 children killed in texas

My cousin was one of them

**Comment by VillainsRule4000** [comment]
> My cousin was one of them

I feel incredibly sorry for you. It must be hard to have that happen to a close member of your family.
